using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Dlp.Authenticator.DataContracts {

    /// <summary>
    /// Class containing the result of a user authentication process.
    /// </summary>
    public sealed class AuthenticateUserResponse : AbstractResponse {

        /// <summary>
        /// Instantiates the AuthenticateResponse class.
        /// </summary>
        public AuthenticateUserResponse() : base() { }

        /// <summary>
        /// Gets the token generated by the authentication service to identify the user session.
        /// </summary>
        public string AuthenticationToken { get; set; }

        /// <summary>
        /// Gets the user unique identification key at authentication service.
        /// </summary>
        public Guid UserKey { get; set; }

        /// <summary>
        /// Gets the user name registered at authentication service.
        /// </summary>
        public string Name { get; set; }
    }
}
